// =====================================================
// legit.js — legitimate (safe) alerts mixed into every
//            round. Depends on config.js (TPL).
// =====================================================
"use strict";

/* ---- Legitimate (safe) alerts. Mixed into every round. ---- */
const LEGIT = [
  { template: TPL.WIN11,    title: "Application Crash", message: "Adobe Photoshop has stopped working. Windows is checking for a solution to the problem.", meta: "Exception: 0xc0000005 (Access Violation)  |  Module: photoshop.exe" },
  { template: TPL.WIN11,    title: "Disk Space Warning", message: "You are running low on disk space on Local Disk (C:). Click here to free up space using Disk Cleanup.", meta: "Drive C: 2.1GB free of 256GB  |  Action: Optional" },
  { template: TPL.WIN11,    title: "Windows Update", message: "Updates are available. Your device will restart outside of active hours to finish updating.", meta: "Update: KB5034441  |  Size: 1.2GB  |  Source: Microsoft Update Catalog" },
  { template: TPL.WIN11,    title: "DLL Missing", message: "The program can't start because MSVCP140.dll is missing from your computer. Try reinstalling the program.", meta: "Application: game.exe  |  Required: VC++ Redistributable 2015-2022" },
  { template: TPL.WIN11,    title: "Certificate Expired", message: "Your connection is not private. NET::ERR_CERT_DATE_INVALID — The certificate for this site has expired.", meta: "Issuer: Let's Encrypt  |  Domain: example{tld}  |  Self-signed: No" },
  { template: TPL.WIN11,    title: "Permission Denied", message: "Access denied. You need administrator privileges to modify files in C:\\Windows\\System32.", meta: "User: StandardUser  |  Required: Administrator  |  UAC: Enabled" },
  { template: TPL.WIN11,    title: "Low Memory", message: "Your computer is low on memory. Save your files and close programs to prevent data loss.", meta: "Physical: 15.2GB/16GB used  |  Top consumer: Chrome (8.4GB)" },
  { template: TPL.TERMINAL, title: "node.exe", message: "Error: listen EADDRINUSE: address already in use :::3000. Another process is already running on this port.", meta: "Port: 3000  PID: 12847  Protocol: TCP" },
  { template: TPL.WIN11,    title: "Startup Repair", message: "Startup Repair couldn't repair your PC. Press 'Advanced options' to try other recovery methods.", meta: "Log: SrtTrail.txt  |  Attempts: 3/3  |  Boot: Failed" },
  { template: TPL.TOAST,    title: "NVIDIA GeForce", message: "A new driver update is available. Version 551.23 — Game Ready Driver.", meta: "Current: 546.01  ·  New: 551.23  ·  Signed: NVIDIA Corporation" },
  { template: TPL.BIOS,     title: "BSOD: KERNEL_DATA_INPAGE_ERROR", message: "Your PC ran into a problem and needs to restart. We're just collecting some error info, and then we'll restart for you.", meta: "Stop code: 0x0000007A  Dump: C:\\Windows\\MEMORY.DMP" },
  { template: TPL.WIN11,    title: "Windows Firewall", message: "Windows Defender Firewall has blocked some features of Spotify on all public and private networks.", meta: "Program: Spotify.exe  |  Rule: Inbound TCP  |  Action: Block" },
  { template: TPL.WIN11,    title: "OneDrive Sync Error", message: "OneDrive couldn't sync your files. There's not enough space on your OneDrive to upload these files.", meta: "Used: 4.99GB of 5GB  |  Files pending: 342" },
  { template: TPL.WIN11,    title: "Print Spooler Error", message: "Operation could not be completed. The print spooler service is not running.", meta: "Service: Spooler  |  Printer: HP LaserJet M404  |  Error: 0x800706B5" },
  { template: TPL.WIN11,    title: "Microsoft Teams", message: "Microsoft Teams has encountered an unexpected error and needs to close. Your recent activity may not have been saved.", meta: "Version: 23247.1112  |  Exception: Unhandled  |  Module: teams.exe" },
  { template: TPL.TOAST,    title: "Windows Security", message: "Windows Security has finished scanning your PC. No threats were found. Your device is protected.", meta: "Scanned: 284,932 files  ·  Threats: 0  ·  Today 10:42 AM" },
  { template: TPL.WIN11,    title: "IP Conflict", message: "Windows has detected an IP address conflict. Another computer on this network has the same IP address.", meta: "IP: 192.168.1.105  |  Adapter: Intel Wi-Fi 6 AX201" },
  { template: TPL.WIN11,    title: "Activation Required", message: "Windows isn't activated. Go to Settings to activate Windows now.", meta: "Edition: Windows 11 Home  |  Error: 0xC004F213" },
  { template: TPL.WIN11,    title: "Steam Download Error", message: "An error occurred while updating Counter-Strike 2 (disk write error). Please check your disk for errors.", meta: "App: Counter-Strike 2  |  Drive: D:\\  |  Free: 12.4GB" },
  { template: TPL.WIN11,    title: "Chrome: Out of Memory", message: "Aw, Snap! Something went wrong while displaying this webpage. Error code: Out of Memory.", meta: "Tab: 47 open  |  Process: chrome.exe  |  RAM used: 9.2GB" },
  { template: TPL.TOAST,    title: "Bluetooth Pairing Failed", message: "Windows couldn't connect to AirPods Pro. Make sure your Bluetooth device is in range and try again.", meta: "Device: AirPods Pro  ·  Error: 0x80070490" },
  { template: TPL.WIN11,    title: "Registry Backup", message: "Registry backup completed successfully. A backup has been saved to C:\\Windows\\System32\\config\\RegBack.", meta: "Size: 142MB  |  Timestamp: Today 03:00 AM" },
  { template: TPL.WIN11,    title: "Task Scheduler Error", message: "Task Scheduler failed to start the task 'GoogleUpdateTaskMachineCore' because the user account is no longer valid.", meta: "Task: GoogleUpdateTaskMachineCore  |  Error: 0x80070534" },
  { template: TPL.TERMINAL, title: "MSBuild", message: "Build failed. Error MSB3073: The command exited with code 1. See the build log for details.", meta: "Project: MyApp.csproj  Exit code: 1  Log: bin\\Debug\\build.log" },
  { template: TPL.WIN11,    title: "SFC: Corrupted Files", message: "Windows Resource Protection found corrupt files but was unable to fix some of them.", meta: "Command: sfc /scannow  |  Corrupted: 3 files  |  Fixed: 1" },
  { template: TPL.WIN11,    title: "DirectX Runtime Error", message: "The application has requested the Runtime to terminate it in an unusual way. DirectX 12 initialization failed.", meta: "Error: D3D12_ERROR_INVALID_REDIST  |  GPU: RTX 4070" },
  { template: TPL.WIN11,    title: "Audio Service Stopped", message: "The Windows Audio service has stopped. Right-click the speaker icon in the taskbar to troubleshoot.", meta: "Service: AudioSrv  |  Error: 0x8007045B  |  Device: Realtek HD" },
  { template: TPL.TERMINAL, title: "git merge", message: "CONFLICT (content): Merge conflict in src/main.js. Automatic merge failed; fix conflicts and then commit.", meta: "Branch: feature/login -> main  Conflicts: 3 files" },
  { template: TPL.TERMINAL, title: "npm install", message: "npm ERR! code ERESOLVE. Unable to resolve dependency tree. peer react@^16.0.0 requires incompatible version.", meta: "Installed: react@18.2.0  Peer: react@^16.0.0" },
  { template: TPL.TERMINAL, title: "python", message: "ModuleNotFoundError: No module named 'numpy'. The script cannot continue without this dependency.", meta: "Script: analyze.py  Python: 3.11.2  Fix: pip install numpy" },
  { template: TPL.WIN11,    title: "Hyper-V Not Available", message: "Hyper-V cannot be installed: A hypervisor is already running. VirtualBox may conflict with Hyper-V.", meta: "Error: HV_STATUS_HYPERVISOR_PRESENT  |  Conflict: VirtualBox 7.0" },
  { template: TPL.WIN11,    title: "Event Log Full", message: "The Windows Security event log is full. Some events may not be recorded until the log is cleared.", meta: "Log: Security  |  Size: 20MB/20MB  |  Events lost: 4,821" },
  { template: TPL.AV,       title: "SSD Health Warning", message: "S.M.A.R.T. attribute warning: Reallocated Sectors detected on WD Blue 1TB SSD. Back up data now.", meta: "Drive: WD Blue 1TB (C:) · Reallocated: 12 · Tool: CrystalDiskInfo 9.3" },
  { template: TPL.WIN11,    title: "WSL Failed to Start", message: "WSL 2 failed to start. Please check that virtualization is enabled in your UEFI firmware settings.", meta: "Error: 0x80370102  |  Fix: Enable VT-x in BIOS" },
  { template: TPL.WIN11,    title: "Font Cache Rebuild", message: "Windows font cache service has reset. Some applications may display fonts incorrectly until restart.", meta: "Service: FontCache3.0.0.0  |  Fonts: 1,042 registered" },
  { template: TPL.WIN11,    title: "Hyper-V Checkpoint", message: "Hyper-V Manager failed to merge checkpoint. Virtual machine disk may be in an inconsistent state.", meta: "VM: DevServer-2024  |  Checkpoint: 3 pending  |  Error: 0x80070490" },
  { template: TPL.TERMINAL, title: "netsh", message: "Windows Sockets reset is required to fix network connectivity. Run 'netsh winsock reset' as administrator.", meta: "Error: WSAENOTSOCK  Stack: TCP/IP  Adapter: Realtek PCIe" },
  { template: TPL.WIN11,    title: "Outlook PST Corrupted", message: "Outlook detected errors in the file outlook.pst. Run Inbox Repair Tool (scanpst.exe) to fix the issue.", meta: "File: outlook.pst  |  Size: 18.4GB  |  Tool: scanpst.exe" },
  { template: TPL.TERMINAL, title: "java", message: "Exception in thread 'main': java.lang.OutOfMemoryError: Java heap space. Increase -Xmx JVM argument.", meta: "Heap: 512MB  Used: 511MB  Fix: -Xmx2g" },
  { template: TPL.BIOS,     title: "BSOD: MEMORY_MANAGEMENT", message: "Your PC ran into a problem and needs to restart. We're collecting error info.", meta: "Stop code: 0x0000001A  RAM: 32GB DDR5  Test: memtest86+" },
  { template: TPL.TOAST,    title: "Malwarebytes", message: "Malwarebytes failed to update its threat database. Check your internet connection and try again.", meta: "Definitions: v2024.12.01 outdated  ·  Retry in: 15 min" },
  { template: TPL.WIN11,    title: "Time Sync Failed", message: "Windows Time service failed to synchronize with time.windows{tld}. Your system clock may be inaccurate.", meta: "Server: time.windows{tld}  |  Error: 0x800705B4  |  Offset: +47s" },
  { template: TPL.WIN11,    title: "COM Surrogate Crash", message: "COM Surrogate has stopped working. This may affect thumbnail previews and file type handlers.", meta: "Process: dllhost.exe  |  Exception: 0xc000027b" },
  { template: TPL.TOAST,    title: "Disk Optimizer", message: "Drive optimization has been scheduled. Defragmenting C: drive will improve performance over time.", meta: "Drive: C: (HDD)  ·  Fragmentation: 23%  ·  Wednesday 01:00 AM" },
  { template: TPL.WIN11,    title: "Xbox Game Bar Error", message: "Xbox Game Bar couldn't start. The Windows Gaming Overlay encountered an error. Check if GameDVR is enabled.", meta: "Service: GameDVR  |  Error: 0x80073D02" },
  { template: TPL.WIN11,    title: "Remote Desktop Warning", message: "Remote Desktop Connection: The certificate from the remote computer could not be verified. Do you want to connect anyway?", meta: "Remote: 10.0.0.12  |  Certificate: Self-signed" },
  { template: TPL.WIN11,    title: "Recycle Bin Corrupted", message: "The Recycle Bin on C: is corrupted. Do you want to empty the Recycle Bin for this drive?", meta: "Drive: C:\\  |  Bin: $Recycle.Bin  |  Items lost: Unknown" },
  { template: TPL.WIN11,    title: "Update Rollback", message: "Cumulative Update KB5039239 failed to install and has been rolled back automatically by Windows.", meta: "Update: KB5039239  |  Size: 987MB  |  Error: 0x800F0922" },
  { template: TPL.WIN11,    title: "Microsoft Edge Update", message: "Microsoft Edge has been updated to version 126.0.2592.68. Restart the browser to apply the changes.", meta: "Channel: Stable  |  Source: Microsoft Update  |  Signed: Yes" },
  { template: TPL.TOAST,    title: "Discord", message: "Discord PTB has a new update available. Restart the app to install (52 MB).", meta: "Version: 1.0.9012  ·  Source: Discord Inc.  ·  Signed: Yes" },
  { template: TPL.WIN11,    title: "USB Device Unrecognized", message: "One of the USB devices connected to this computer has malfunctioned. Try disconnecting and reconnecting the device.", meta: "Device: Unknown USB Device  |  Port: USB 3.0 Hub  |  Code: 43" },
  { template: TPL.WIN11,    title: "Microsoft Store", message: "App updates are downloading in the background. Office and other apps may restart automatically when updates finish.", meta: "Apps updating: 4  |  Source: Microsoft Store  |  Action: None" },
  { template: TPL.TERMINAL, title: "docker", message: "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?", meta: "Service: docker  Status: Stopped  Last started: --" },
  { template: TPL.TERMINAL, title: "cargo build", message: "error[E0277]: the trait `Display` is not implemented for `Foo`. Required because of the bound in `print_it`.", meta: "Crate: my_app  Tool: cargo 1.78.0  Profile: release" },
  { template: TPL.WIN11,    title: "Power Throttling", message: "Your laptop is on battery and has entered power-saving mode. Background apps will be paused to extend battery life.", meta: "Battery: 18%  |  Plan: Battery Saver  |  Throttle: ON" },
  { template: TPL.WIN11,    title: "Display Scaling Changed", message: "You changed your display scaling. Some apps may not look right until they're restarted.", meta: "Scale: 125%  |  Display: Built-in (1920×1200)  |  Action: Restart apps" },
  { template: TPL.TOAST,    title: "Calendar", message: "Standup with team — starts in 5 minutes (Microsoft Teams meeting).", meta: "Outlook  ·  11:00 AM  ·  Org: contoso{tld}" },
  { template: TPL.WIN11,    title: "Camera Privacy", message: "Microsoft Teams is now using your camera. Click here to manage which apps can access your camera.", meta: "App: ms-teams.exe  |  Allowed: Yes  |  Setting: Privacy" },
  { template: TPL.WIN11,    title: "Microsoft 365", message: "Your Microsoft 365 Family subscription expires in 14 days. Renew now to avoid losing access to Office apps and 1 TB of OneDrive storage.", meta: "Plan: Family  |  Expires: 2026-06-05  |  Renewal: Auto" },
  { template: TPL.TOAST,    title: "VPN Disconnected", message: "Your corporate VPN connection has dropped. Reconnecting automatically — please wait.", meta: "Server: us-east-1  ·  Provider: Corp-VPN  ·  Reconnect: 1/3" },
  { template: TPL.TOAST,    title: "Bluetooth Battery Low", message: "Your Microsoft Surface Pen battery is at 8%. Replace the AAAA cell soon to avoid losing pressure sensitivity.", meta: "Device: Surface Pen  ·  Battery: 8%  ·  Connected: Yes" },
  { template: TPL.TERMINAL, title: "pip install", message: "Successfully installed numpy-1.24.3 pandas-2.0.1 scipy-1.10.1. Cleaning up build artifacts.", meta: "Python: 3.11.2  Source: pypi{tld}  Venv: .venv" },
  { template: TPL.WIN11,    title: "AMD Adrenalin", message: "A new AMD Radeon driver is available (24.5.1). Download and install to improve performance in recent titles.", meta: "Current: 23.12.1  |  New: 24.5.1  |  Signed: AMD Inc." },
  { template: TPL.WIN11,    title: "Snipping Tool Updated", message: "Snipping Tool has been updated. Try the new Text Actions feature to copy or redact text directly from screenshots.", meta: "Version: 11.2402.34.0  |  Source: Microsoft Store" },
  { template: TPL.WIN11,    title: "Sticky Notes", message: "Couldn't sync your Sticky Notes to the cloud. You can still access local notes; sync will retry automatically.", meta: "Sync: Failed  |  Notes: 7 unsynced  |  Retry: 5 min" },
  { template: TPL.WIN11,    title: "Family Safety", message: "Screen time limit reached for the 'kids' account. Sign in as a parent to extend or wait until tomorrow.", meta: "User: kids  |  Limit: 2h  |  Used: 2h 00m" },
  { template: TPL.TOAST,    title: "Slack", message: "New direct message from @alex — \"hey, got a minute?\"", meta: "Channel: DM  ·  Workspace: contoso  ·  1m ago" },
  { template: TPL.WIN11,    title: "App Package Damaged", message: "An app you installed can't be opened because its package is damaged. Reinstall from the Microsoft Store to fix this.", meta: "App: Notepad++  |  Source: Store  |  Action: Reinstall" },
  { template: TPL.WIN11,    title: "BitLocker Status", message: "Your drive is encrypted with BitLocker. The recovery key has been backed up to your Microsoft account.", meta: "Drive: C:  |  Status: Encrypted  |  Recovery key: Backed up" },
  { template: TPL.TOAST,    title: "Outlook Calendar", message: "You have 3 unread meeting invites from this week. Open Outlook to review.", meta: "Pending: 3 invites  ·  Source: Outlook Desktop" },
  { template: TPL.TERMINAL, title: "kubectl", message: "error: You must be logged in to the server (Unauthorized). Run 'kubectl auth' to refresh credentials.", meta: "Context: production  Cluster: us-east-1" },
  { template: TPL.WIN11,    title: "Driver Verifier", message: "Driver Verifier Manager detected a non-conforming driver. Restart in safe mode to remove it.", meta: "Driver: nvlddmkm.sys  |  Code: 0x000000C9" },
  { template: TPL.TOAST,    title: "Steam", message: "Counter-Strike 2 has finished downloading. Click to play.", meta: "App: CS2  ·  Size: 39.2 GB  ·  Status: Ready" },
  { template: TPL.WIN11,    title: "Mail Sync Error", message: "We couldn't sync your inbox. Check your account password and try again.", meta: "Account: outlook  |  Last sync: 2 hours ago  |  Error: 0x80048820" },
  { template: TPL.WIN11,    title: "Storage Sense", message: "Storage Sense ran cleanup. Freed 12.8 GB by removing temporary files and old downloads.", meta: "Freed: 12.8 GB  |  Items: 4,217  |  Next run: 7 days" },
  { template: TPL.TERMINAL, title: "vite", message: "VITE v5.2.10  ready in 482 ms.  Local: http://localhost:5173/", meta: "Bundler: vite  Port: 5173" },
  { template: TPL.WIN11,    title: "Windows Hello", message: "Windows Hello couldn't recognize your face. Try again or use a PIN to sign in.", meta: "Camera: IR  |  Attempts: 3  |  Fallback: PIN" },
  { template: TPL.WIN11,    title: "Defender Quick Scan", message: "Periodic scanning ran a quick scan in the background — no threats found.", meta: "Scan: Quick  |  Duration: 1m 47s  |  Threats: 0" },
  { template: TPL.TOAST,    title: "Spotify", message: "Now playing: Daily Mix 3 — 23 tracks queued.", meta: "Spotify  ·  4:21 / 3:42:18" },
  { template: TPL.WIN11,    title: "Auto HDR Enabled", message: "Auto HDR is now enabled for Forza Horizon 5. Restart the game to apply the new color profile.", meta: "Game: Forza Horizon 5  |  HDR: ON  |  Display: HDR-capable" },
  { template: TPL.TERMINAL, title: "ssh", message: "Permission denied (publickey). Check that your private key is loaded via 'ssh-add'.", meta: "Host: dev-bastion.corp  Key: ~/.ssh/id_ed25519" },
  { template: TPL.WIN11,    title: "Compatibility Lost", message: "An app you installed is no longer compatible with the latest Windows update. Reinstall to continue using it.", meta: "App: LegacyToolKit  |  Compat: Lost  |  Action: Reinstall" },
  { template: TPL.WIN11,    title: "Battery Report", message: "Your laptop battery has lost 8% of its design capacity this year. Replacement recommended in 18+ months.", meta: "Wear: 8%  |  Cycles: 384  |  Health: Normal" },
  { template: TPL.TOAST,    title: "Outlook", message: "Meeting starting now: Sprint Review with the engineering team.", meta: "Outlook  ·  Sprint Review  ·  Now" },
  { template: TPL.WIN11,    title: "Indexing Paused", message: "Search indexing has been paused because the device is on battery. Resume when plugged in.", meta: "Indexer: WSearch  |  State: Paused  |  Reason: Power saver" },
  { template: TPL.TERMINAL, title: "psql", message: "FATAL: password authentication failed for user 'app'. Check your DATABASE_URL.", meta: "Host: db.internal  User: app  Code: 28P01" },
  { template: TPL.TOAST,    title: "Screenshot Saved", message: "Screen snip copied to clipboard and saved to Pictures > Screenshots.", meta: "File: Screenshot 2026-05-22 152412.png  ·  Size: 348 KB" },
  { template: TPL.WIN11,    title: "Storage Spaces", message: "Storage Spaces detected a pool drive is degraded. Replace drive 2 within 7 days to avoid data loss.", meta: "Pool: MainPool  |  Drive: 2  |  Status: Degraded" },
  { template: TPL.WIN11,    title: "Windows Sandbox", message: "Windows Sandbox closed. All changes inside the sandbox have been discarded as expected.", meta: "Session: 18m 42s  |  Apps run: 2  |  State: Discarded" },
  { template: TPL.TOAST,    title: "GitHub Desktop", message: "Your branch is behind 'origin/main' by 4 commits. Pull to sync.", meta: "Branch: feature/login  ·  Behind: 4 commits" },
  { template: TPL.TERMINAL, title: "make", message: "make: *** [all] Error 2. See output above for compiler errors in src/parser.c.", meta: "Target: all  Errors: 1  Tool: gcc 13.2.0" },
  { template: TPL.WIN11,    title: "Network Reset", message: "Network reset completed. Reinstall any VPN clients to restore custom configurations.", meta: "Adapters: Reset  |  Profiles: Cleared  |  Action: Reinstall VPN" },
  { template: TPL.TOAST,    title: "Surface Audio", message: "Surface Headphones 2+ disconnected unexpectedly. Reconnect to resume audio.", meta: "Device: Surface Headphones 2+  ·  Battery: 14%" },
  { template: TPL.WIN11,    title: "Display Driver Updated", message: "Intel UHD Graphics driver updated to 31.0.101.4953. Restart your PC for the new driver to take effect.", meta: "Driver: igfxHK.sys  |  Version: 31.0.101.4953  |  Source: Microsoft Update" },
  { template: TPL.WIN11,    title: "Thermal Throttle", message: "Your CPU briefly throttled due to high temperatures during a heavy task. Performance is back to normal.", meta: "Peak: 92°C  |  Now: 64°C  |  Duration: 4s" },
  { template: TPL.WIN11,    title: "Display Signal Restored", message: "HDMI signal on display 2 has been restored. The previous interruption lasted 0.4 seconds.", meta: "Display: 2  |  Resolution: 2560×1440 @ 144 Hz  |  HDR: Off" },
  { template: TPL.TERMINAL, title: "df -h", message: "/dev/sda1  465G  421G  41G  92% / — drive nearly full, consider freeing space.", meta: "Filesystem: ext4  Mounted: /  Free: 41G" },
  { template: TPL.WIN11,    title: "Time Synced", message: "Windows Time service has synchronized your system clock with time.windows{tld}.", meta: "Server: time.windows{tld}  |  Offset: +0.3s  |  Next sync: 24h" },
  { template: TPL.TOAST,    title: "OneDrive Vault", message: "Personal Vault relocked after 20 minutes of inactivity. Sign in to unlock.", meta: "OneDrive  ·  Last access: 23 min ago" },
  { template: TPL.TOAST,    title: "Helpdesk", message: "Ticket #4821 was resolved. Please rate your experience in the helpdesk portal.", meta: "Ticket: #4821  ·  Status: Resolved  ·  Portal: helpdesk.corp" },
  { template: TPL.WIN11,    title: "Dell BIOS Update", message: "A new BIOS update (1.21.0) is available for your Dell XPS. Download from Dell Support to install.", meta: "Model: XPS 15 9520  |  Current: 1.18.0  |  New: 1.21.0  |  Signed: Dell Inc." },
  { template: TPL.TERMINAL, title: "speedtest", message: "Download: 487.4 Mbps · Upload: 23.8 Mbps · Ping: 12 ms · Jitter: 1.4 ms", meta: "Server: Stockholm  Tool: speedtest-cli 2.1.3" },
  { template: TPL.WIN11,    title: "Cloud Clipboard", message: "Cloud Clipboard is now syncing across your signed-in Windows devices. Manage in Settings > System > Clipboard.", meta: "Devices: 3  |  Status: Active  |  Setting: System > Clipboard" },
  { template: TPL.WIN11,    title: "Mouse Settings", message: "Pointer precision is enabled. Open Settings > Bluetooth & devices > Mouse to adjust pointer speed.", meta: "Pointer speed: 6/10  |  Enhance precision: ON" },
  { template: TPL.TOAST,    title: "Outlook", message: "Reconnected to the Exchange server after a brief drop. No data was lost.", meta: "Server: outlook.office365{tld}  ·  Drop: 2.1s" },
  { template: TPL.WIN11,    title: "Runtime Missing", message: "A required Visual C++ 2015-2022 Redistributable is missing. Download it from Microsoft Support to install.", meta: "Required: MSVCP140.dll  |  Source: Microsoft Support" },
  { template: TPL.WIN11,    title: "Windows Memory Diagnostic", message: "Windows Memory Diagnostic finished. Your RAM is functioning normally — no errors detected.", meta: "Test: Standard  |  Duration: 18m  |  Errors: 0" },
  { template: TPL.TOAST,    title: "Security Advisory", message: "A security advisory was published for Google Chrome. Update to version 126.0.6478.183 to apply the patch.", meta: "CVE: 2026-3201  ·  Severity: High  ·  Update: Available" },
  { template: TPL.WIN11,    title: "Windows Security", message: "Windows Security found and quarantined 1 threat during a routine scan. No action needed.", meta: "Scanned: 142,891 files  |  Threats: 1 (quarantined)  |  Time: 11:47" },
  { template: TPL.WIN11,    title: "OneDrive Sync", message: "Your OneDrive has finished syncing. 142 files were uploaded since your last sign-in.", meta: "Files: 142  |  Account: signed in  |  Status: Up to date" },
  { template: TPL.WIN11,    title: "Empty Recycle Bin?", message: "There are 347 items in your Recycle Bin. Empty it to free 4.2 GB on Local Disk (C:)?", meta: "Items: 347  |  Size: 4.2 GB  |  Drive: C:" },
  { template: TPL.WIN11,    title: "Variable Refresh Rate", message: "Variable Refresh Rate is now active for fullscreen games. Smoother frame pacing should be visible.", meta: "Display: G-SYNC  |  Range: 30-144 Hz  |  Status: Enabled" },
  { template: TPL.TOAST,    title: "Print Job Complete", message: "Your print job 'budget-q3.pdf' finished. 4 pages printed on HP LaserJet M404.", meta: "Pages: 4  ·  Printer: HP LaserJet M404  ·  Status: Done" },
  { template: TPL.WIN11,    title: "OneNote Sync", message: "Your OneNote notebook finished syncing. 12 new pages from your other devices are now available.", meta: "Notebook: Personal  |  Pages: 12  |  Last sync: 2 min ago" },
  { template: TPL.WIN11,    title: "Defender Real-time", message: "Real-time protection has resumed after a brief pause during the system update.", meta: "Service: WinDefend  |  Status: Active  |  Last pause: 4 min" },
  { template: TPL.TOAST,    title: "Microsoft Edge", message: "Edge is up to date. Latest version: 127.0.2651.86.", meta: "Channel: Stable  ·  Version: 127.0.2651.86" },
  { template: TPL.WIN11,    title: "Battery Connected", message: "Your laptop is now charging. Estimated full charge in 1 hour 24 minutes.", meta: "Battery: 38%  |  Charging  |  1h 24m to full" },
  { template: TPL.TERMINAL, title: "git pull", message: "Already up to date. 0 files changed, 0 insertions(+), 0 deletions(-).", meta: "Branch: main  Remote: origin" },
  { template: TPL.WIN11,    title: "Network Drive", message: "Network drive Z: has been reconnected after a brief outage. All open files are synced.", meta: "Drive: Z:  |  Server: corp-files  |  Status: Connected" },
  { template: TPL.TERMINAL, title: "npm run build", message: "Build completed successfully in 28.4s. Output written to dist/.", meta: "Files: 47  Size: 2.1 MB  Tool: webpack 5.92" },
  { template: TPL.WIN11,    title: "Color Calibration", message: "Display color profile has been applied. Calibration complete.", meta: "Profile: sRGB Standard  |  Gamma: 2.2  |  Brightness: 250 nits" },
  { template: TPL.TOAST,    title: "Microsoft Teams", message: "Sarah is calling — Microsoft Teams.", meta: "Caller: Sarah K.  ·  Type: Audio call" },
  { template: TPL.WIN11,    title: "Disk Cleanup", message: "Disk Cleanup finished. Freed 1.8 GB by removing temporary files and old logs.", meta: "Freed: 1.8 GB  |  Method: Auto  |  Drive: C:" },
  { template: TPL.WIN11,    title: "Restore Point Created", message: "A system restore point has been created automatically before the recent driver update.", meta: "Name: Pre-driver-update  |  Drive: C:  |  Size: 1.2 GB" },
  { template: TPL.WIN11,    title: "App Permissions", message: "Microsoft Photos has requested access to your Pictures folder. Allow?", meta: "App: Photos  |  Permission: Pictures  |  First request" },
  { template: TPL.TOAST,    title: "Slack", message: "@channel — Sprint planning starts in 10 minutes.", meta: "Workspace: corp  ·  Calendar reminder  ·  10 min" },
  { template: TPL.TERMINAL, title: "pytest", message: "===== 47 passed, 3 skipped, 0 failed in 14.2s =====", meta: "Suite: test_core  Python: 3.11" },
  { template: TPL.WIN11,    title: "Power Mode", message: "Your device switched to Best Performance mode while plugged in.", meta: "Mode: Best Performance  |  Plan: AC profile" },
  { template: TPL.TOAST,    title: "Outlook", message: "Out-of-office reply enabled for the weekend.", meta: "Outlook  ·  Active until Mon 9 AM" },
  { template: TPL.WIN11,    title: "Focus Assist", message: "Focus assist is now active. Notifications will be silenced until 5 PM.", meta: "Mode: Focus  |  Until: 5:00 PM  |  Apps allowed: Priority" },
  // ---- Additional legit alerts (variety pass) ----
  { template: TPL.WIN11,    title: "Windows Update Ready", message: "An update is ready to install. Windows will restart after working hours unless you choose to install now.", meta: "Update: KB5037851  |  Size: 482 MB  |  Reboot: required", icon: "warning" },
  { template: TPL.TOAST,    title: "Microsoft 365", message: "Word recovered an unsaved document. Click to restore.", meta: "File: Untitled - Recovered  ·  Source: Word AutoRecover", icon: "question" },
  { template: TPL.WIN11,    title: "Defender Definitions Updated", message: "Microsoft Defender threat definitions updated successfully. Your device is protected.", meta: "Version: 1.413.998.0  |  Signed: Microsoft", icon: "blank" },
  { template: TPL.TERMINAL, title: "yarn install", message: "Done in 23.41s. 1,284 packages installed, 0 vulnerabilities reported.", meta: "Manager: yarn 1.22.22  Cache: ~/.yarn/cache" },
  { template: TPL.TERMINAL, title: "pnpm install", message: "Lockfile is up to date, resolution step is skipped. Already up to date.", meta: "pnpm 9.1.4  Workspace: 4 packages" },
  { template: TPL.TERMINAL, title: "deno run", message: "Granted env access to '~/.config/myapp'. Server listening on http://localhost:8000", meta: "Deno 1.44.4  Permissions: env, net" },
  { template: TPL.WIN11,    title: "Storage Sense Reminder", message: "Storage Sense hasn't run for 30 days. Run cleanup now to free up space on Local Disk (C:)?", meta: "Last run: 2026-04-21  |  Drive: C: (12.4 GB free)", icon: "warning" },
  { template: TPL.WIN11,    title: "Windows Spotlight", message: "Today's lock screen picture is available. Learn more about this image from Bing.", meta: "Source: Windows Spotlight  |  Region: Iceland", icon: "blank" },
  { template: TPL.TOAST,    title: "Phone Link", message: "iPhone 15 connected. You can now send messages and answer calls from your PC.", meta: "Device: iPhone 15  ·  Battery: 84%" },
  { template: TPL.WIN11,    title: "Defender Cloud Block", message: "Microsoft Defender blocked a potentially unwanted application based on cloud reputation. No action needed.", meta: "Blocked: PUA:Win32/InstallCore  |  Source: Cloud", icon: "warning" },
  { template: TPL.TOAST,    title: "Spotify", message: "Discover Weekly is ready. 30 fresh tracks added to your queue.", meta: "Playlist: Discover Weekly  ·  Updated Mondays" },
  { template: TPL.WIN11,    title: "Cumulative Update Installed", message: "May 2026 Cumulative Update has been installed. Your device will restart tonight at 3:30 AM unless overridden.", meta: "Update: KB5036893  |  Restart: 03:30  |  Signed: Microsoft", icon: "warning" },
  { template: TPL.WIN11,    title: "WSL: New Distro Available", message: "Ubuntu 24.04 LTS is now available in the Microsoft Store for WSL. Install to upgrade from 22.04.", meta: "Distro: Ubuntu-24.04  |  Source: Microsoft Store", icon: "blank" },
  { template: TPL.TERMINAL, title: "vite build", message: "✓ built in 4.82s. 14 chunks emitted to ./dist (832.4 KB total, 271.1 KB gzipped).", meta: "Bundler: vite 5.3.1" },
  { template: TPL.TERMINAL, title: "esbuild", message: "Build complete. 1 entry point, 0 errors, 2 warnings. 142 KB output.", meta: "Tool: esbuild 0.21.5" },
  { template: TPL.WIN11,    title: "WiFi: Connected", message: "Connected to 'Cafe-Public-WiFi'. This network may be unsecured. Sensitive sites may not work.", meta: "Network: Cafe-Public-WiFi  |  Security: WPA2-PSK", icon: "warning" },
  { template: TPL.TOAST,    title: "Battery Saver", message: "Battery saver is on. Background apps and push notifications are limited until the device is plugged in.", meta: "Battery: 19%  ·  Mode: Saver" },
  { template: TPL.WIN11,    title: "Windows Backup", message: "Windows Backup finished. Files, settings, and credentials backed up to your Microsoft account.", meta: "Backup size: 4.2 GB  |  Account: signed in", icon: "blank" },
  { template: TPL.TERMINAL, title: "apt upgrade", message: "0 packages upgraded, 0 newly installed, 0 to remove. System is up to date.", meta: "OS: Debian 12  Tool: apt 2.6.1" },
  { template: TPL.TERMINAL, title: "systemctl status nginx", message: "● nginx.service - active (running) since Fri 2026-05-23 09:14:32 UTC; 3h 21min ago", meta: "Service: nginx  Status: active  PID: 8412" },
  { template: TPL.WIN11,    title: "Edge Profile Sync", message: "Microsoft Edge finished syncing your favorites, passwords, and history across your signed-in devices.", meta: "Devices: 3  |  Last sync: just now", icon: "blank" },
  { template: TPL.TOAST,    title: "Google Drive", message: "Google Drive synced 12 new files from your Documents folder.", meta: "Account: rasmus@…  ·  Synced: 12 files" },
  { template: TPL.WIN11,    title: "BitLocker Recovery Key Saved", message: "Your BitLocker recovery key has been saved to your Microsoft account. You can view it at account.microsoft{tld}.", meta: "Drive: C:  |  Account: signed in", icon: "blank" },
  { template: TPL.WIN11,    title: "Hyper-V Manager", message: "Virtual machine 'DevServer-2024' has been gracefully shut down.", meta: "VM: DevServer-2024  |  Uptime: 4h 12m", icon: "blank" },
  { template: TPL.TOAST,    title: "Microsoft Teams", message: "Daily standup reminder — starting in 10 minutes.", meta: "Meeting: Daily standup  ·  10 min" },
  { template: TPL.WIN11,    title: "Realtek Audio Driver", message: "Audio device driver updated. You may need to restart applications using audio.", meta: "Driver: Realtek HD Audio  |  Version: 6.0.9614.1", icon: "warning" },
  { template: TPL.TOAST,    title: "Calendar", message: "Tomorrow: Dentist appointment at 10:00. Block your calendar 30 min before?", meta: "Outlook  ·  Tomorrow  ·  10:00" },
  { template: TPL.WIN11,    title: "Microsoft Store", message: "All apps are up to date. Microsoft Store will check again in 1 day.", meta: "Apps checked: 47  |  Updates: 0", icon: "blank" },
  { template: TPL.TERMINAL, title: "rustup update", message: "info: latest update on 2026-05-15, rust version 1.78.0. info: cleaning up downloads & tmp directories", meta: "Channel: stable  Toolchain: x86_64-pc-windows-msvc" },
  { template: TPL.WIN11,    title: "Display Color Profile", message: "Color calibration has been applied. Display is now using sRGB IEC61966-2.1 color profile.", meta: "Profile: sRGB  |  Display: ASUS PG279QM", icon: "blank" },
  { template: TPL.TOAST,    title: "Outlook", message: "You have 2 new emails from 'Customer Support'.", meta: "Outlook  ·  Inbox  ·  2 new" },
  { template: TPL.WIN11,    title: "Microsoft Office Repair", message: "Office Quick Repair finished successfully. Restart Word or Excel to load the repaired components.", meta: "Tool: Office Quick Repair  |  Duration: 4m 22s", icon: "blank" },
  { template: TPL.WIN11,    title: "WSL Memory Reclaimed", message: "WSL2 reclaimed 1.4 GB of memory back to Windows. Subsystem will continue running normally.", meta: "Distro: Ubuntu-22.04  |  Reclaimed: 1.4 GB", icon: "blank" },
  { template: TPL.WIN11,    title: "Steam Cloud Sync", message: "Cloud sync for Cyberpunk 2077 finished. Your saves are up to date across devices.", meta: "Game: Cyberpunk 2077  |  Files: 47", icon: "blank" },
  { template: TPL.WIN11,    title: "Visual Studio Update", message: "Visual Studio 2022 17.10.2 has been installed. Restart VS to apply the changes.", meta: "Version: 17.10.2  |  Channel: Release", icon: "warning" },
  { template: TPL.TOAST,    title: "GitHub Actions", message: "Workflow 'CI · main' completed successfully in 2m 47s.", meta: "Repo: sixtenhaglund/ThreatDetect  ·  Branch: main" },
  { template: TPL.WIN11,    title: "Windows Search Index Rebuild", message: "Search indexing has been rebuilt. Search results should appear normally again.", meta: "Indexed: 412,873 items  |  Duration: 28m", icon: "blank" },
  { template: TPL.TOAST,    title: "Notion", message: "New comment on your 'Sprint Planning' page from @maria.", meta: "Notion  ·  Page: Sprint Planning  ·  1m ago" },
  { template: TPL.WIN11,    title: "USB Device Connected", message: "USB Mass Storage Device 'KINGSTON' is ready to use as drive (E:).", meta: "Device: KINGSTON USB  |  Drive: E:  |  Format: NTFS", icon: "blank" },
  { template: TPL.WIN11,    title: "Webcam In Use", message: "Microsoft Teams is using your camera. Toggle camera privacy in Settings > Privacy & Security > Camera.", meta: "App: ms-teams.exe  |  Camera: Built-in HD", icon: "warning" },
  { template: TPL.TOAST,    title: "Dropbox", message: "Dropbox finished uploading 'Vacation_2026.zip' (1.2 GB) to your account.", meta: "Dropbox  ·  Uploaded: 1.2 GB" },
  { template: TPL.WIN11,    title: "Battery Discharging Quickly", message: "Battery is draining faster than usual. Top consumers: Chrome (37%), Slack (12%), Spotify (6%).", meta: "Drain rate: -28%/h  |  Time left: ~2h 10m", icon: "warning" },
  { template: TPL.TERMINAL, title: "cargo test", message: "test result: ok. 84 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 12.04s", meta: "Crate: my_app  Tool: cargo 1.78.0" },
  { template: TPL.WIN11,    title: "Privacy Settings Synced", message: "Privacy choices for your Microsoft account have been updated across all signed-in devices.", meta: "Devices updated: 3  |  Source: account.microsoft{tld}", icon: "blank" },
  { template: TPL.TOAST,    title: "Twitch", message: "Streamer 'shroud' is live now: Counter-Strike 2.", meta: "Twitch  ·  shroud · CS2 · 12.4K viewers" },
  { template: TPL.WIN11,    title: "Optional Driver Available", message: "Logitech G Hub driver update available. Install via Windows Update (Optional updates).", meta: "Driver: Logitech G Hub  |  Version: 2024.7.451", icon: "warning" },
  { template: TPL.TERMINAL, title: "make install", message: "Install complete. 142 files copied to /usr/local. Add /usr/local/bin to PATH if not already.", meta: "Target: install  Prefix: /usr/local" },
  { template: TPL.WIN11,    title: "OneDrive Files On-Demand", message: "Some files in OneDrive are only available online. Right-click and choose 'Always keep on this device' to make them available offline.", meta: "Online-only: 1,847 files  |  Account: signed in", icon: "blank" },
  { template: TPL.WIN11,    title: "Defender SmartScreen", message: "SmartScreen has blocked a download because it's not commonly downloaded. You can keep it from your downloads.", meta: "Blocked: installer_x64.exe  |  Source: untrusted", icon: "warning" },
  { template: TPL.TOAST,    title: "Slack", message: "Reminder: Sprint demo at 2 PM in #dev-team.", meta: "Slack  ·  #dev-team  ·  2:00 PM" },
  { template: TPL.WIN11,    title: "Game Mode Activated", message: "Game Mode is now active for Forza Horizon 5. Background apps and Windows Update are paused.", meta: "Game: Forza Horizon 5  |  Mode: Active", icon: "blank" },
  { template: TPL.TERMINAL, title: "ssh-keygen", message: "Generating public/private ed25519 key pair. Your identification has been saved in ~/.ssh/id_ed25519.", meta: "Type: ed25519  Output: ~/.ssh/id_ed25519" },
  { template: TPL.WIN11,    title: "Microsoft Account: New Sign-In", message: "New sign-in to your Microsoft account from Stockholm, Sweden. If this wasn't you, secure your account now.", meta: "Location: Stockholm  |  Device: Chrome on Windows", icon: "warning" },
  { template: TPL.TOAST,    title: "Discord", message: "Your nitro subscription renews in 7 days. Update payment method to avoid interruption.", meta: "Discord Nitro  ·  Renews in 7 days" },
  // ---- Theme-balancing pass: more legit cards in virus-heavy themes ----
  // Mouse / cursor (virus-heavy because of CURSOR)
  { template: TPL.WIN11,    title: "Logitech Options+", message: "Logitech Options+ updated to version 1.82.471. Restart the app to use the new gesture mappings.", meta: "App: Logitech Options+  |  Version: 1.82.471  |  Signed: Logitech, Inc.", icon: "blank" },
  { template: TPL.TOAST,    title: "Bluetooth Battery Low", message: "Microsoft Sculpt Comfort Mouse battery is at 12%. Replace AA cells in the next few days.", meta: "Device: Sculpt Comfort Mouse  ·  Battery: 12%" },
  { template: TPL.WIN11,    title: "Pointer Precision", message: "Enhance pointer precision has been disabled per your settings. New mouse-tracking behavior is now active.", meta: "Setting: Mouse  |  Source: Settings app" },
  { template: TPL.WIN11,    title: "Touchpad Gestures Reset", message: "Three-finger swipe gestures have been reset to defaults after the recent driver update.", meta: "Device: Precision Touchpad  |  Driver: Synaptics 19.5.34" },
  // Boot / BIOS / UEFI (virus-heavy because of ROOTKIT)
  { template: TPL.BIOS,     title: "Secure Boot Enabled", message: "Secure Boot is currently ON. Boot order changes will require admin authentication on next reboot.", meta: "SecureBoot: ON  Mode: UEFI  TPM: 2.0" },
  { template: TPL.WIN11,    title: "Dell BIOS Update Available", message: "BIOS 1.23.0 is available for your Dell XPS 15 9520. Download from Dell Support to install.", meta: "Model: XPS 15 9520  |  Current: 1.21.0  |  New: 1.23.0  |  Signed: Dell Inc.", icon: "warning" },
  { template: TPL.WIN11,    title: "Fast Startup Restored", message: "Fast Startup was re-enabled automatically after the May 2026 cumulative update finished.", meta: "Feature: Fast Startup  |  Status: ON", icon: "blank" },
  { template: TPL.WIN11,    title: "Boot Order Changed", message: "Boot priority changed in UEFI: Windows Boot Manager now precedes USB. Reboot to apply.", meta: "Priority: 1) Windows Boot Manager  2) USB  3) Network", icon: "warning" },
  // Legacy Windows / IE / Win32 (virus-heavy because of OLDEXE)
  { template: TPL.WIN11,    title: "Internet Explorer Mode", message: "Microsoft Edge loaded this internal site in IE Mode for compatibility with a legacy intranet app.", meta: "Site: intranet.corp  |  Mode: IE 11  |  Source: Group Policy", icon: "blank" },
  { template: TPL.WIN11,    title: "Visual C++ Runtime", message: "Microsoft Visual C++ 2015-2022 Redistributable (x64) was updated. Restart applications using it.", meta: "Package: VC++ 14.40  |  Signed: Microsoft", icon: "blank" },
  { template: TPL.TERMINAL, title: "powershell", message: "Loading Windows PowerShell 2.0 engine for compatibility with a legacy script. .NET 2.0 runtime active.", meta: "Engine: PSv2.0  Script: legacy_admin.ps1" },
  { template: TPL.WIN11,    title: "Win32 Component Repair", message: "Windows Component Store (CBS) repair finished. All Win32 components are healthy — no further action needed.", meta: "Tool: DISM /RestoreHealth  |  Duration: 14m 22s", icon: "blank" },
  // Audio (very few legit cards before)
  { template: TPL.WIN11,    title: "Default Output Changed", message: "Default audio output switched to Headphones (Realtek HD Audio) after device was plugged in.", meta: "Output: Headphones  |  Driver: Realtek HD Audio", icon: "blank" },
  { template: TPL.TOAST,    title: "Microphone Permission", message: "Microsoft Teams is now using your microphone. Toggle in Settings > Privacy > Microphone.", meta: "App: ms-teams.exe  ·  Mic: Built-in" },
  { template: TPL.TOAST,    title: "Spotify", message: "Local audio output switched to Sonos Beam. Now playing on living room speaker.", meta: "Spotify  ·  Output: Sonos Beam" },
  // ---- New visual template legit cards (so the new styles aren't all-virus) ----
  { template: TPL.MAC,      title: "Mail", message: "3 new emails from Engineering — Sprint planning notes attached.", meta: "Inbox  ·  3 new" },
  { template: TPL.MAC,      title: "Phone Link", message: "Your iPhone is now connected. Calls and messages will appear here.", meta: "Device: iPhone 15  ·  Connected" },
  { template: TPL.CHAT,     title: "Sarah K.", message: "Hey — code review on your PR is done. LGTM, ready to merge whenever.", meta: "Slack  ·  #reviews  ·  2m" },
  { template: TPL.CHAT,     title: "Alex", message: "Want to grab lunch at 12? The new ramen place opened on the corner.", meta: "Teams  ·  DM  ·  just now" },
  { template: TPL.PHONE,    title: "Maps", message: "Leave in 15 minutes for your 2:00 PM appointment to avoid traffic.", meta: "ETA: 22 min  ·  via Sveavägen" },
  { template: TPL.PHONE,    title: "Battery", message: "iPhone battery is at 20%. Connect to a charger soon.", meta: "Battery: 20%" },
  // ---- PRINT legit cards (heavily tokenized — each draw shows different filenames,
  //      printers, page counts, cities, etc. using the legit-flavored pools). ----
  { template: TPL.PRINT,    title: "{filename}{ext}", message: "Ready to print on {printer}. {pagecount} pages, color, double-sided.", meta: "Printer: {printer}  |  Pages: {pagecount}  |  Mode: Duplex" },
  { template: TPL.PRINT,    title: "Boarding_Pass{ext}", message: "Print boarding pass — SAS flight SK1234 to {city}. Single page, color.", meta: "Printer: {printer}  |  Pages: 1" },
  { template: TPL.PRINT,    title: "Receipt{ext}", message: "Print receipt for purchase at {brand} Store, {city}. Total: 459 SEK.", meta: "Printer: {printer}  |  Pages: 1" },
  { template: TPL.PRINT,    title: "Tax_Return_2025{ext}", message: "Print all tax documents. Total: {pagecount} pages, black-and-white only.", meta: "Printer: {printer}  |  Pages: {pagecount}  |  Color: OFF" },
  { template: TPL.PRINT,    title: "Vacation_Photo{ext}", message: "Print 4x6 photo to {printer}. High-quality glossy paper recommended.", meta: "Printer: {printer}  |  Size: 4x6 in" },
  { template: TPL.PRINT,    title: "Calendar_{filename}{ext}", message: "Print monthly calendar. {pagecount} pages, color.", meta: "Printer: {printer}  |  Pages: {pagecount}" },
  { template: TPL.PRINT,    title: "Recipe{ext}", message: "Print recipe to take into the kitchen. {pagecount} pages.", meta: "Printer: {printer}  |  Pages: {pagecount}" },
  { template: TPL.PRINT,    title: "Concert_Ticket{ext}", message: "Print {brand} event ticket. Show at the door. Single page.", meta: "Printer: {printer}  |  Pages: 1" },
  { template: TPL.PRINT,    title: "Shipping_Label{ext}", message: "Print shipping label for delivery to {city}. Adhesive label paper recommended.", meta: "Printer: {printer}  |  Pages: 1" },
  { template: TPL.PRINT,    title: "{filename}{ext}", message: "Final draft for {department}. Ready to print on {printer} — {pagecount} pages.", meta: "Printer: {printer}  |  Pages: {pagecount}  |  Dept: {department}" },
  { template: TPL.CAPTCHA,  title: "Cloudflare Verification", message: "Cloudflare is checking your browser before redirecting you to github{tld}. This should only take a few seconds.", meta: "Ray ID: 8a7c92f1  ·  Performance & security by Cloudflare" },
  { template: TPL.UPDATE,   title: "ThreatDetect", message: "ThreatDetect has been updated locally. Reload the page to get the latest viruses and minigames.", meta: "Local build  ·  No network update required", icon: "blank" },
  // ---- BSOD legit cards (real Windows kernel crashes do happen).
  //      Tokens like {stopcode}, {sysmodule}, {cpu}, {diagtool} get swapped at
  //      deal time so each draw reads slightly differently. ----
  { template: TPL.BSOD,     title: "MEMORY_MANAGEMENT", message: "A problem has been detected and Windows has been shut down to prevent damage to your computer. Your PC will restart automatically.", meta: "STOP: {stopcode} (0x00041790, 0x0000001B, 0x00000000, 0x00000000)" },
  { template: TPL.BSOD,     title: "IRQL_NOT_LESS_OR_EQUAL", message: "A driver tried to access an invalid memory address. Windows has collected information and will restart.", meta: "STOP: {stopcode}  |  Failed module: {sysmodule}" },
  { template: TPL.BSOD,     title: "WHEA_UNCORRECTABLE_ERROR", message: "Your PC ran into a hardware problem and needs to restart. We're just collecting some error info, and then we'll restart for you.", meta: "STOP: {stopcode}  |  CPU: {cpu}  |  Likely cause: thermal" },
  { template: TPL.BSOD,     title: "PAGE_FAULT_IN_NONPAGED_AREA", message: "Windows hit a page fault and is restarting. If this keeps happening, try running Windows Memory Diagnostic.", meta: "STOP: {stopcode}  |  Tool: {diagtool}" },
  { template: TPL.BSOD,     title: "KERNEL_SECURITY_CHECK_FAILURE", message: "Your PC ran into a problem and needs to restart. We're just collecting some error info, and then we'll restart for you.", meta: "STOP: {stopcode}  |  No download required — automatic recovery" },
  // ---- WIN311 legit cards (legacy emulators + retro software) ----
  { template: TPL.WIN311,   title: "DOSBox-X", message: "DOSBox-X started successfully. Mounting C: as ~/dos/games. Type EXIT to leave the emulator.", meta: "Emulator: DOSBox-X 2025.05.01  |  Mode: SVGA  |  Source: dosbox-x{tld}" },
  { template: TPL.WIN311,   title: "Program Manager", message: "WinWorldPC retro VM started. Windows 3.11 running in QEMU for legitimate vintage software preservation.", meta: "VM: QEMU  |  Image: win311.vhd  |  Source: winworldpc{tld}" },
  { template: TPL.WIN311,   title: "Notepad", message: "README.TXT loaded. This file describes the legacy data format used by the 1996-era export tool.", meta: "File: README.TXT  |  Encoding: ASCII  |  Size: 4 KB" },
  { template: TPL.WIN311,   title: "Solitaire", message: "SOL.EXE running in vintage compatibility mode. Score: 4520. Resume game in progress?", meta: "Compatibility: Win 3.x  |  Wrapper: Wine 8.0" }
];

/* ============================================================
   DEATHS — virus-specific death animation metadata
   (CSS classes live in the <style> block: .death-<VIRUS>)
   ============================================================ */


